doctrine:
  dbal:
    host: '%env(DATABASE_HOST)%'
    port: '%env(DATABASE_PORT)%'
    dbname: '%env(DATABASE_NAME)%'
    user: '%env(DATABASE_USER)%'
    password: '%env(DATABASE_PASSWORD)%'
    driver: pdo_pgsql
    server_version: 13.3
    charset: UTF8

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Store:
        type: attribute
        dir: '%kernel.project_dir%/src/Store/Domain/Entity'
        prefix: 'App\Store\Domain\Entity'
