# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_listener: true
#  view:
#    mime_types:
#      json:
#        - 'application/json'
#    view_response_listener: true
#  format_listener:
#    rules:
#      - { path: ^/test, prefer_extension: true, fallback_format: json, priorities: [ json ] }
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
